# Generated by Django 4.2.13 on 2024-06-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_remove_storage_owner_box_owner_alter_box_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name': 'Ячейка', 'verbose_name_plural': 'Ячейки'},
        ),
        migrations.RemoveField(
            model_name='storage',
            name='volume',
        ),
    ]
