# Generated by Django 4.2.13 on 2024-06-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_box_options_remove_storage_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='number',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='номер'),
            preserve_default=False,
        ),
    ]
