# Generated by Django 4.2.13 on 2024-06-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_box_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='feature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='особенность'),
        ),
    ]
