# Generated by Django 4.2.13 on 2024-06-27 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_storage_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='email')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('completed', 'Обработана')], db_index=True, default='new', max_length=255, verbose_name='статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='дата обработки')),
            ],
            options={
                'verbose_name': 'заказы консультаций',
            },
        ),
    ]
