# Generated by Django 4.2.13 on 2024-06-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_consultation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'заказ консультации', 'verbose_name_plural': 'заказы консультаций'},
        ),
        migrations.AddField(
            model_name='rent',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('not_paid', 'Не оплачено')], db_index=True, default='not_paid', max_length=50, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='rent',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
