# Generated by Django 4.2.13 on 2024-06-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_alter_consultation_options_rent_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
    ]
