# Generated by Django 4.2.13 on 2024-06-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_rent_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='is_active',
        ),
        migrations.AddField(
            model_name='rent',
            name='is_empty',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Пустая'),
        ),
    ]
