# Generated by Django 4.2.13 on 2024-06-29 12:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_remove_rent_is_empty_box_is_empty_rent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='номер телефона'),
        ),
    ]
