# Generated by Django 4.2.13 on 2024-06-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_rent_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='rent',
            name='rent_status',
            field=models.CharField(choices=[('new', 'Ожидает обработки'), ('processed', 'Ожидает оплаты'), ('delivery', 'Доставка вещей на склад'), ('active', 'Активная'), ('inactive', 'Неактивная'), ('expired', 'Просрочена')], db_index=True, default='new', max_length=50, verbose_name='Статус аренды'),
        ),
    ]
