# Generated by Django 4.2.13 on 2024-06-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_remove_rent_payment_status_rent_rent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='is_empty',
        ),
        migrations.AddField(
            model_name='box',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Доступна для аренды'),
        ),
    ]
