# Generated by Django 4.2.13 on 2024-06-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0017_remove_box_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rent_status',
            field=models.CharField(choices=[('new', 'Ожидает обработки'), ('processed', 'Ожидает оплаты'), ('delivery', 'Доставка вещей на склад'), ('active', 'Активная'), ('inactive', 'Неактивная'), ('expired', 'Просрочена')], db_index=True, default='new', max_length=50, verbose_name='Статус'),
        ),
    ]
