# Generated by Django 4.2.13 on 2024-06-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Адрес клиента'),
        ),
    ]
